version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:latest

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Build the Haskell package
          command: stack build

      - run:
          name: Test the Haskell package
          command: stack test
